# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "sam-app"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "sam-fourth-dynamodb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cuo5tr0pv58s"
s3_prefix = "sam-fourth-dynamodb"
region = "us-east-1"
disable_rollback = true
image_repositories = []

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
